{% set name = "griffe" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: 48c667ad51a7f756238f798866203aeb8f9fa02d4192e25970f57f813bb37f26

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - griffe = griffe.cli:main

requirements:
  host:
    - python >=3.8
    - pdm >2
    - pdm-backend
  run:
    - python >=3.8
    - colorama >=0.4

test:
  imports:
    - griffe
    - griffe.loader
    - griffe.docstrings.parsers
    - griffe.dataclasses
  commands:
    - griffe -h
    #- griffe dump
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - dbast
